name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Check out this repo
      - uses: actions/checkout@v2

      # Check out the default branch for the Graylog docker repo
      - uses: actions/checkout@v2
        with:
          name: Graylog2/graylog-docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Get docker tags
        shell: bash
        run: |
          echo "##[set-output name=tags;]$(./docker-tags.sh ${{secrets.DOCKERHUB_USERNAME}}/graylog-docker-arm ${{ steps.get_branch.outputs.branch }} $(cat graylog-docker/VERSION))"
        id: get_docker_tags

      - name: Build and push image
        run: cd graylog-docker && docker buildx build --platform linux/arm/v8 --output 'type=image,push=true' ${{ steps.get_docker_tags.outputs.tags }} --build-arg GRAYLOG_VERSION=$(cat VERSION) .
